### ISSUE TITLE
Add option to set cookies

### ISSUE THREAD

**Issue by Keldorb** [whoot/Typo3Scan#1]
Hey!
Good work with the Tool. It would be nice if you can add a paramater to give the tool cookies. This could handle pre-authentication while pentesting.

**Comment by whoot** [comment]
Hey,

thanks for the feedback. Im currently rewriting the whole tool, because the typo3 guys made a lot of security improvements (which is good for users, but bad for me :p)
However, I will keep your suggestion in mind.

For now i pushed an UNTESTED quick and dirty solution.

**Comment by Keldorb** [comment]
Nice, i will give it a shot today.

Edit: Dosnt work for me

Typo-Enumerator finished at 2018-03-07 11:43:27

Traceback (most recent call last):
  File "typo3_enumerator.py", line 195, in <module>
    main.run()
  File "typo3_enumerator.py", line 146, in run
    Typo3_Installation.run(domain)
  File "/root/tools/Typo-Enumerator/lib/check_installation.py", line 34, in run
    check_on_root = Typo3_Installation.check_root(domain)
  File "/root/tools/Typo-Enumerator/lib/check_installation.py", line 50, in check_root
    response = Request.get_request(domain.get_name(), '/')
  File "/root/tools/Typo-Enumerator/lib/request.py", line 45, in get_request
    cookie = {config['cookie'].split(

Edit2:
A progress bar would be nice too :)

**Comment by whoot** [comment]
Should work now! Forgot to set a default value, that was the reason for the error.

**Comment by whoot** [comment]
Seems to work. Closed.
