### ISSUE TITLE
i have problem when scan 

### ISSUE THREAD

**Issue by shadihh9** [whoot/Typo3Scan#10]
HTTPSConnectionPool(host='www.emp.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa9b1fecbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "typo3scan.py", line 199, in <module>
    main.run()
  File "typo3scan.py", line 70, in run
    check.check_root()
  File "/root/Typo3Scan/lib/domain.py", line 96, in check_root
    if re.search('powered by TYPO3', response['html']):
TypeError: 'NoneType' object is not subscriptable

**Comment by whoot** [comment]
Well, maybe its because the site is not reachable.
You probably arent allowed to scan it anyway ;)
