### ISSUE TITLE
List known vulnerabilities

### ISSUE THREAD

**Issue by whoot** [whoot/Typo3Scan#11]
TODO: Parameter or something to show known vulnerabilties for Core and Extensions

**Comment by definity** [comment]
Do you have a reference or anything to get started on this?

**Comment by whoot** [comment]
Nope. The idea was to just list the database entries.

E.g.: Show me a list of all core vulns in version 9.7.3: ```--core 9.7.3```
Or: Show me all vulns of tt_news: ```--ext tt_news```

Something like that...

**Comment by whoot** [comment]
Done with v0.7-dev

**Comment by definity** [comment]
Very cool.  Question - will the vulnerabilities be included in scan results... i.e. Core 9.7.3 detected and has known vulnerabilities?  Or would this be more appropriate for a separate issue.

**Comment by whoot** [comment]
> Very cool. Question - will the vulnerabilities be included in scan results... i.e. Core 9.7.3 detected and has known vulnerabilities? Or would this be more appropriate for a separate issue.

Uhm.. This is the main functionality of this tool :D
You can even see that in the screenshot in the readme.

**Comment by definity** [comment]
> > Very cool. Question - will the vulnerabilities be included in scan results... i.e. Core 9.7.3 detected and has known vulnerabilities? Or would this be more appropriate for a separate issue.
> 
> Uhm.. This is the main functionality of this tool :D
> You can even see that in the screenshot in the readme.

Whoops!  I knew that.  My bad. 🙄
