### ISSUE TITLE
It seems that Typo3 is not used on this domain

### ISSUE THREAD

**Issue by safebaseline** [whoot/Typo3Scan#13]
![图片](https://user-images.githubusercontent.com/38883009/104693417-95599200-5744-11eb-8c0b-ac3db46017d1.png)

**Comment by whoot** [comment]
Please describe your problem. Otherwise I cant help.

**Comment by safebaseline** [comment]
When I scan the website！it can’t work well！please see the screenshot！the error show the picture ！



发自我的iPhone


------------------ Original ------------------

**Comment by whoot** [comment]
First, manually check that Typo3 is really used on the affected domain.

If so, please be aware that I cant help you, if you do not disclose the URL to me. If you cant disclose it (which is understandable) you have to fix the issue on your own.

**Comment by mjulda** [comment]
I'd like to ask.
almost every domain i scan does not work, like the problem above.
[x] It seems that Typo3 is not used on this domain

**Comment by mjulda** [comment]
I'd like to ask.
almost every domain i scan does not work, like the problem above.
[x] It seems that Typo3 is not used on this domain

**Comment by safebaseline** [comment]
已收到

**Comment by whoot** [comment]
> I'd like to ask. almost every domain i scan does not work, like the problem above. [x] It seems that Typo3 is not used on this domain

Are you 100% sure that the websites use Typo3? If so, it would be helpful if you could give me more information about the websites. On which sites does the problem occur?
Again, please be aware that I cant help you, if you do not disclose the URL or any information to me. If you cant disclose it (which is understandable) you have to fix the issue on your own. Try to read and understand the code on your own and see which check fails.

**Comment by mjulda** [comment]
Thanks for the response, I misunderstood.
It turns out that the target web is not using Typo3.

thanks bro👌
