### ISSUE TITLE
Basic auth option not working

### ISSUE THREAD

**Issue by exploide** [whoot/Typo3Scan#16]
**Describe the bug**\

Invoking `./typo3scan.py -d http://url/ --auth user:pass` has no effect and the basic authentication credentials will not be used.

This is because https://github.com/whoot/Typo3Scan/blob/7fb4fa0183c89683f3a836575c3bd7437f6336eb/lib/request.py#L38 loads the config from a file and ignores the command line options.

**To Reproduce**\
1. Set up a Typo 3 with basic auth in front of it
2. Scan with `./typo3scan.py -d http://url/ --auth user:pass`
3. Observe the message `[x] It seems that Typo3 is not used on this domain`

**Expected behavior**\
Command line option should be taken into consideration.

As a workaround I wrote the credentials into the `config.json` file.

**Comment by whoot** [comment]
thanks for your bug report.
Everything should work as expected now.
I actually wanted to get rid of the configuration file and use parameters instead. But so far I'm not done yet and I guess I forgot to re-enable the corresponding lines.

**Comment by exploide** [comment]
Thanks for your fast response.

Yes it's working now.

But there is the drawback that the credentials are persisted on disk now, i.e. they are written to `config.json` and remain there until the next run.

So I encourage you "to get rid of the configuration file and use parameters instead". :+1:
