### ISSUE TITLE
list index out of range when trying to update

### ISSUE THREAD

**Issue by frederikmoellers** [whoot/Typo3Scan#23]
Whenever I try to run `typo3scan.py -u`, i get an error:

```
[+] Searching for new CORE vulnerabilities...
Traceback (most recent call last):
  File "typo3scan.py", line 209, in <module>
    Update()
  File "lib/update.py", line 41, in __init__
    self.load_core_vulns()
  File "lib/update.py", line 62, in load_core_vulns
    last_page = int(pages[-1])
IndexError: list index out of range
```

It doesn't matter if I reset the database before with `typo3scan.py -r` or not. The scanning itself works fine.

I have tried running it with different Python versions but get the same error on both 3.6 and 3.9. I haven't had time yet to take a look at the source code and identify the root cause. If I find out more, I'm going to post it here.

**Comment by whoot** [comment]
Thanks for pointing out.
They changed the URL to the advisories. Fixed it in the current release.
