### ISSUE TITLE
Links to Advisorys use the wrong Year

### ISSUE THREAD

**Issue by er4z0r** [whoot/Typo3Scan#32]
Thanks for writing and sharing this!

**Describe the bug**\
There seems to be a bug in how the URLs for advisories are constructed. The code seems to be using the current year in places where it shouldn't leading to some URLs being wrong. Correcting the year in the advisory name will get you to the correct advisory.

**To Reproduce**\
Take the following listing
```
 [+] Version Information
  ├ Identified Version:     11.5
  ├ Could not identify exact version.
  ├ Do you want to print all vulnerabilities for branch 11.5? (y/n): y
  └ Known Vulnerabilities:

     [!] TYPO3-CORE-SA-2023-005
      ├ Vulnerability Type: Broken Access Control
      ├ Subcomponent:       Admin Tool (ext:install)
      ├ Affected Versions:  11.5.10 - 11.0.0
      ├ Severity:           Medium
      └ Advisory URL:       https://typo3.org/security/advisory/typo3-core-sa-2023-005

     [!] TYPO3-CORE-SA-2023-004
      ├ Vulnerability Type: Cross-Site Scripting
      ├ Subcomponent:       Frontend Login Mailer (ext:felogin)
      ├ Affected Versions:  11.5.10 - 11.0.0
      ├ Severity:           Medium
      └ Advisory URL:       https://typo3.org/security/advisory/typo3-core-sa-2023-004
```
Try navigating to the advisory for the XSS in Frontend Login Mailer.
Get a 404 error.

**Expected behavior**\
There seems to be an issue in the construction of the URL. When you substitute 2023 with 2022 you actually get the advisory.

**Screenshots**\

**Additional context**\
Ranning latest version from GH (last commit May 14th)

**Comment by whoot** [comment]
Thanks for your bug report. I will look into this

**Comment by whoot** [comment]
Okay, I dont know how it happend and when it happened, but all CMS and extension entries for 2022 were affected.
Deleting the affected entries and using the built in updater worked as intended, therefore its not a programming error.

Anyway. Entries are correct now and everything should work as intended.
Thank a lot for your report!
