### ISSUE TITLE
RFE: Add option for json output file

### ISSUE THREAD

**Issue by doomguy** [whoot/Typo3Scan#4]
Hi,

it would be great to have an option for json logging. This is helpful for integrating your tool into automation workflows.

Maybe something like WhatWeb is doing:
https://github.com/urbanadventurer/WhatWeb
```
--log-json=FILE         Log JSON format.
```

Thanks for your consideration.

**Comment by whoot** [comment]
Will be added in the next release.
Thanks for your input!
