### ISSUE TITLE
Doesn't find version info when other scanner do find them

### ISSUE THREAD

**Issue by DBJRdev** [whoot/Typo3Scan#6]
Checking with latest Typo3Scan: it does not show the Typo3 version of several tested sites, whereas other web-based services manage to figure out (e.g. https://www.t3versions.com/ , tested on our dbjr.de). Are we doing something wrong with Typo3Scan if we don't see the Typo3 version numbers?

**Comment by whoot** [comment]
Thanks for your bug report.
Right now it seems that there is a bug which leads to an incorrect path.

**Comment by whoot** [comment]
Alright, I did analyze the issue and the reason why it does not find the version is quite simple:

**Typo3Scan** just searches for version information in different files - since you blocked access to these files (which is great from a security point of view), it is not possible to determine the version in use.

**T3versions** searches for unique files of various versions. This is a very interesting (and more successful) approach. Implementing this would take a lot of time, which I don't want to spend at the moment.

**Comment by c0decave** [comment]
Ran also into the issue. Added a --force mode. Now it scans anyway.
https://github.com/c0decave/Typo3Scan
Also opening up a pull request in a minute.

**Comment by whoot** [comment]
I had planned this feature already several times, but never found the time to do it.
Really appreciate the pull request. Will look into it in the next days.

**Comment by c0decave** [comment]
> I had planned this feature already several times, but never found the time to do it.
> Really appreciate the pull request. Will look into it in the next days.
Take your time, i introduced a bug here and there and added some other things. I probably push it tomorrow and do some extra testing.

**Comment by definity** [comment]
I have all versions since v9.0.0 downloaded and hashed.  If I get time, I'll try to find some unique files to test... if you have any files that would be good candidates, I can provide you the results.

If you'd like to do it yourself, here's how I did the downloaded everything and did the hashing.

```bash
curl https://get.typo3.org/list/version/9 | grep Download | grep href > v9
curl https://get.typo3.org/list/version/10 | grep Download | grep href > v10
curl https://get.typo3.org/list/version/11 | grep Download | grep href > v11
cat v* | egrep -o "[0-9]+\\.[0-9]+\\.[0-9]+" > versions
for ver in `cat versions`;do echo $ver; curl -sL -o typo3_src_${ver}.tgz https://get.typo3.org/${ver};done

mkdir t
cd t
for ver in `cat ../versions`;do echo Working on - $ver; tar -zxf ../typo3_src_${ver}.tgz; echo " Hashing files for $ver"; find ./ -type f -exec md5sum {} \; > ../typo3_src_${ver}_hashes; echo " Cleaning up..."; export deldir=$(ls); rm -fr ${deldir}; unset deldir; done
```

This last one will result in output looking like
```
Working on - 10.4.13
 Hashing files for 10.4.13
 Cleaning up...
Working on - 10.4.12
 Hashing files for 10.4.12
 Cleaning up...
```

**Comment by definity** [comment]
Also, if you're looking for versions, you might try WhatWeb... I know this tool can do the file checks and hashing so you might see this implemented there as well.
https://github.com/urbanadventurer/WhatWeb/blob/d07a9ac751cd42ee9ed38f3deb2d78efeb59d1d8/plugins/typo3.rb

By the looks of it... it needs some love as it doesn't detect anything recent... let me fix that.

**Comment by whoot** [comment]
Nice catch! Thank you a lot for sharing!

**Comment by definity** [comment]
You're welcome!  Also, I submitted a pull request to update the plugin 😉 
https://github.com/urbanadventurer/WhatWeb/pull/364

**Comment by definity** [comment]
A thought on the implementation compared to WhatWeb... the way that tool is currently implemented, it will make repeated requests for the same file, hash it, and then check if there is a match.  But it does it multiple times

Instead I think it would be more efficient to keep a DB or a list of hashes by file and version.  You request the file once, hash it, then check that hash against the list of hashes for that file to see to which version(s) match.

**Comment by whoot** [comment]
Alright, I got all versions down to 3.3
I have to investigate myself what a good candidate would be and then I will include it in Typo3Scan. Thanks a lot for your help so far @definity !

**Comment by whoot** [comment]
Done with version 0.7
Most versions should be detected, but there is still a lot to sort out.

**Comment by definity** [comment]
What's left to sort out exactly?  Do you have a todo list or something?

**Comment by whoot** [comment]
There are a lot of versions with non-unique files and i have to figure out a common hash for the following major versions:

- 4.8
- 6.2 (if access to ChangeLog is denied)
- 8.1
- 8.6
- 9.x
- 10.x

Also there are ELTS Versions, which are only available for paying customers.
