### ISSUE TITLE
can't run - getting "progressbar" error

### ISSUE THREAD

**Issue by scapegrace13** [whoot/Typo3Scan#7]
Hey guys,

first, nice tool you wrote. With your current version I'm getting issued running it on my latest kali machine.
I can't get it running well. Can you please check this case?

Thanks in advance and best regards
scape

> sudo git clone https://github.com/whoot/Typo3Scan.git /opt/Typo-Enumerator/
sudo pip install -r requirements.txt

>pentest@kali:/opt/Typo-Enumerator$ python typo3scan.py -h
>Traceback (most recent call last):
> File "typo3scan.py", line 32, in <module>
>    from lib.extensions import Extensions
>  File "/opt/Typo-Enumerator/lib/extensions.py", line 24, in <module>
>   from lib.thread_pool import ThreadPool
>  File "/opt/Typo-Enumerator/lib/thread_pool.py", line 22, in <module>
>   from queue import Queue
>ImportError: No module named queue
>pentest@kali:/opt/Typo-Enumerator$ python3 typo3scan.py -h
>Traceback (most recent call last):
>  File "typo3scan.py", line 32, in <module>
>   from lib.extensions import Extensions
>  File "/opt/Typo-Enumerator/lib/extensions.py", line 24, in <module>
>    from lib.thread_pool import ThreadPool
>  File "/opt/Typo-Enumerator/lib/thread_pool.py", line 23, in <module>
>    from progressbar import Bar, AdaptiveETA, Percentage, ProgressBar
>ModuleNotFoundError: No module named 'progressbar'

>pip install --upgrade --force-reinstall progressbar
>pip install --upgrade --force-reinstall progressbar2

edit, I even checked it in with the new directory name:
/opt/Typo3Scan$
With the same error occuring, and you are missing "wheel" in your requirements file.

**Comment by scapegrace13** [comment]
I solved it for me with:
changing /lib/thread_pool.py
Line 22 to "from Queue import Queue" (uppercase Q)

found here:
[https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3/29688081#29688081](url)

**Comment by whoot** [comment]
Hey,

*Queue* is used in Python2 and *queue* is used in Python3.
Typo3Scan is using Python3, so please ensure that you run it with Python3.

E.g. you could use: 
```
python3 -m pip install -r requirements.txt
```
